### PR TITLE
Miscellaneous fixes

### PR DESCRIPTION
**Pull request by apteryks**
Fixes a couple issues spotted while converting the HTML to Texinfo, for integration into Guile.

### CODE REVIEW

**Comment by arthurgleckler** [comment]
Thanks.  Because of the addition of "[R6RS]", I have to ask John.  I'll let you know as soon as I have a reply from him.

**Comment by arthurgleckler** [comment]
John said that this looks good, so I'm merging it.   Thanks for your patience.

**Comment by arthurgleckler** [comment]
Merged and pushed.

**Comment by apteryks** [comment]
@arthurgleckler thanks a lot for your patience and timely reviews!  My experience contributing to the SRFIs specifications has been very smooth thanks to your efforts. Kudos!

**Pull request merged**
